[package]
name = "robinson"
version = "0.1.0"
edition = "2021"
authors = ["Matt Brubeck <mbrubeck@limpet.net>"]

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
image = "0.24.6"
thiserror = "1.0.40"
