[package]
name = "robinson_paint"
version = "0.1.0"
edition = "2021"

[dependencies]
robinson_css = { version = "0.1.0", path = "../robinson_css" }
robinson_layout = { version = "0.1.0", path = "../robinson_layout" }
