[package]
name = "robinson_pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
robinson_layout = { version = "0.1.0", path = "../robinson_layout" }
robinson_paint = { version = "0.1.0", path = "../robinson_paint" }
